In [34]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [35]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18, 
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 119, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10, 12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1]
})

In [36]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35            119               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [37]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [38]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [39]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [40]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667       0.141414        0.727273
1        0.133333       0.101010        0.636364
2        0.200000       0.060606        0.545455
3        0.266667       0.020202        0.272727
4        0.466667       0.080808        0.636364
5        0.733333       0.101010        0.818182
6        0.400000       1.000000        0.181818
7        0.173333       0.020202        0.818182
8        0.533333       0.151515        1.000000
9        0.000000       0.040404        0.363636
10       1.000000       0.131313        0.727273
11       0.293333       0.131313        0.909091
12       0.666667       0.010101        0.090909
13       0.866667       0.050505        0.454545
14       0.093333       0.000000        0.000000
15       0.333333       0.090909        0.727273

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size=0.25,random_state=42)

In [42]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [43]:
model.compile(optimizer = 'sgd',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [45]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4, verbose = 0
)
#verbose means jo training ho raha hai usme kya ho raha hai ..wo show hoga 0 pe kuch show nhi hoga 1 pe dikhega